ECON-T:
 RW:
  MFC_ALGORITHM_SEL_DENSITY:
   registers:
    algo:
     params:
      select:
       param_value: 0
  
  FMTBUF_ALL:
   registers:
    tx_sync_word: 
     value: 0x122
    config:
     params:
      eporttx_numen:
       param_value: 13
  
  ALGO_THRESHOLD_VAL:
   registers:
    threshold_val_*:
     value: [0x3fffff, 0x3fffff, 0x3fffff, 0x3fffff, 0x3fffff, 0x3fffff, 0x3fffff, 0x3fffff,
             0x3fffff, 0x3fffff, 0x3fffff, 0x3fffff, 0x3fffff, 0x3fffff, 0x3fffff, 0x3fffff,
             0x3fffff, 0x3fffff, 0x3fffff, 0x3fffff, 0x3fffff, 0x3fffff, 0x3fffff, 0x3fffff,
             0x3fffff, 0x3fffff, 0x3fffff, 0x3fffff, 0x3fffff, 0x3fffff, 0x3fffff, 0x3fffff,
             0x3fffff, 0x3fffff, 0x3fffff, 0x3fffff, 0x3fffff, 0x3fffff, 0x3fffff, 0x3fffff,
             0x3fffff, 0x3fffff, 0x3fffff, 0x3fffff, 0x3fffff, 0x3fffff, 0x3fffff, 0x3fffff]
