ECON-T:
 RW:
  MISC_ALL:
   registers:
    misc_rw_0:
     params:
      run:
       param_value: 1

  FCTRL_ALL:
   registers:
    config:
     params:
      invert_command_rx:
       param_value: 0
      EdgeSel_T1:
       param_value: 0
  
  PLL_ALL:
   registers:
    pll_bytes_26to25:
     params:
      output_clk_sel:
       param_value: 0
      ref_clk_sel:
       param_value: 1
    pll_bytes_17to13:
     params:
      VCObypass:
       param_value: 0
    pll_bytes_21to18:
     params:
      fromMemToLJCDR_lfEnable:
       param_value: 0

 RO:
  FCTRL_ALL:
   registers:
    status: 
     params:
      locked:
       param_value: 0
      fc_error:
       param_value: 0
      command_rx_inverted:
       param_value: 0
  
  PLL_ALL:
   registers:
    pll_read_bytes_2to0:
     params:
      lfState:
       param_value: 0
      lfLocked:
       param_value: 0
      lfInstLock:
       param_value: 0
      lfLossOfLockCount:
       param_value: 0
      smState: 
       param_value: 0
      smLocked:
       param_value: 0
    pll_read_bytes_4to3:
     params:
      pll_not_locked_timeout:
       param_value: 0

  MISC_ALL:
   registers:
    misc_ro_0:
     params:
      PUSM_state:
       param_value: 0