ECON-T:
 RW:
  CH_ALIGNER_*INPUT_ALL:
   registers:
    config:
     params:
      prbs_chk_en:
       param_value: 1
      per_ch_align_en:
       param_value: 1
      sel_override_en:
       param_value: 0
      prbs28_en:
       param_value: 1
    sel_override_val:
     value: 0
     
  FMTBUF_ALL:
   registers:
    tx_sync_word:
     value: 0b00100100010
    config:
     params:
      eporttx_numen:
       # Number of output ports enabled
       param_value: 13

  MFC_ALGORITHM_SEL_DENSITY:
   registers:
    algo:
     params:
      select:
       param_value: 0
  
  MISC_ALL:
   registers:
    misc_rw_0:
     params:
      rw_ecc_err_clr:
       param_value: 1