ECON-T:
 RW:
  CH_ALIGNER_*INPUT_ALL:
   registers:
    config:
     params:
      patt_en:
       param_value: 0
      patt_sel:
       param_value: 0
      prbs_chk_en:
       param_value: 1
      prbs28_en:
       param_value: 0
     
  FMTBUF_ALL:
   registers:
    tx_sync_word:
     value: 0b00100100010
    config:
     params:
      eporttx_numen:
       # Number of output ports enabled
       param_value: 13

  MFC_ALGORITHM_SEL_DENSITY:
   registers:
    algo:
     params:
      select:
       param_value: 0
 