ECON-T:
 RW: 
  MFC_ALGORITHM_SEL_DENSITY:
   registers:
    algo:
     params:
      select:
       param_value: 0
      density:
       param_shift: 0

 RO:
  CH_ALIGNER_*INPUT_ALL:
   registers:
     status:
      params:
       prbs_chk_err:
        param_value: 0
       orbsyn_fc_err:
        param_value: 0
       orbsyn_arr_err: 
        param_value: 0
       orbsyn_hdr_err:
        param_value: 0
       align_seu_err:
        param_value: 0
       hdr_mm_err:
        param_value: 0
       snapshot_dv:
        param_value: 0
       pattern_match:
        param_value: 0
     select:
      value: 0
     snapshot: 
      value: 0
