ECON-T:
        
 RW:
  MFC_ALGORITHM_SEL_DENSITY:
   registers:
    algo:
     params:
      select:
       params_value: 0

  ALGO_THRESHOLD_VAL:
   threshold_val_*:
    value [0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0,
           0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 
           0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 
           0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 
           0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 
           0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0]

  FMTBUF_ALL:
   registers:
    buff_t1:
     value: 0x152
    buff_t2:
     value: 0x1ff
    buff_t3:
     value: 0x19
    config:
     params:
      eporttx_numen:
       param_value: 0xc
      stc_type:
       param_value: 0x0
      use_sum:
       param_value: 0x0
